//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Los campos declarados acá corresponden 1 a 1 a los controles con
//     runat="server" definidos en IniciarSesion.aspx. Si se agregan o
//     renombran controles en el .aspx, Visual Studio va a regenerar este
//     archivo automáticamente al guardar.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageUp.UI
{
    public partial class IniciarSesion
    {
        protected global::System.Web.UI.WebControls.Panel pnlLogin;
        protected global::System.Web.UI.WebControls.Panel pnlMensajeLogin;
        protected global::System.Web.UI.WebControls.Literal litMensajeLogin;

        protected global::System.Web.UI.WebControls.TextBox txtLoginEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLoginEmail;

        protected global::System.Web.UI.WebControls.LinkButton lnkOlvideContrasena;
        protected global::System.Web.UI.WebControls.TextBox txtLoginPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLoginPassword;

        protected global::System.Web.UI.WebControls.Button btnIniciarSesion;

        protected global::System.Web.UI.WebControls.Panel pnlRecuperarSolicitar;
        protected global::System.Web.UI.WebControls.Panel pnlMensajeRecuperarSolicitar;
        protected global::System.Web.UI.WebControls.Literal litMensajeRecuperarSolicitar;

        protected global::System.Web.UI.WebControls.TextBox txtRecuperarEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvRecuperarEmail;

        protected global::System.Web.UI.WebControls.Button btnEnviarCodigoRecuperacion;
        protected global::System.Web.UI.WebControls.LinkButton lnkVolverALoginDesdeSolicitar;

        protected global::System.Web.UI.WebControls.Panel pnlRecuperarActualizar;
        protected global::System.Web.UI.WebControls.Panel pnlMensajeRecuperarActualizar;
        protected global::System.Web.UI.WebControls.Literal litMensajeRecuperarActualizar;

        protected global::System.Web.UI.WebControls.TextBox txtCodigoRecuperacion;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCodigoRecuperacion;

        protected global::System.Web.UI.WebControls.TextBox txtNuevaPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNuevaPassword;

        protected global::System.Web.UI.WebControls.TextBox txtConfirmarNuevaPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvConfirmarNuevaPassword;
        protected global::System.Web.UI.WebControls.CompareValidator cvNuevaPassword;

        protected global::System.Web.UI.WebControls.Button btnActualizarPassword;
        protected global::System.Web.UI.WebControls.LinkButton lnkReenviarCodigoRecuperacion;

        protected global::System.Web.UI.WebControls.Panel pnlRecuperarExito;
        protected global::System.Web.UI.WebControls.LinkButton lnkVolverALoginDesdeExito;
    }
}
