//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Los campos declarados acá corresponden 1 a 1 a los controles con
//     runat="server" definidos en MisEspacios.aspx. Los controles que
//     están dentro de <ItemTemplate> del Repeater (lnkEditar, lnkPublicar,
//     lnkPausar, lnkDarDeBaja) NO se declaran acá: solo son accesibles
//     con FindControl dentro de los eventos del Repeater.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageUp.UI
{
    public partial class MisEspacios
    {
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        protected global::System.Web.UI.WebControls.Panel pnlFormularioEspacio;
        protected global::System.Web.UI.WebControls.Literal litTituloFormulario;

        protected global::System.Web.UI.WebControls.TextBox txtNombreEspacio;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombreEspacio;

        protected global::System.Web.UI.WebControls.TextBox txtTipoEspacio;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTipoEspacio;

        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;

        protected global::System.Web.UI.WebControls.Button btnGuardarEspacio;
        protected global::System.Web.UI.WebControls.LinkButton lnkCancelarEdicion;

        protected global::System.Web.UI.WebControls.Literal litSinEspacios;
        protected global::System.Web.UI.WebControls.Repeater rptMisEspacios;
    }
}
