//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Los campos declarados acá corresponden 1 a 1 a los controles con
//     runat="server" definidos en MisReservas.aspx. Los controles que están
//     dentro de <ItemTemplate> del Repeater (lnkCancelar, litComentarioResolucion)
//     NO se declaran acá: solo son accesibles con FindControl dentro de los
//     eventos del Repeater.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageUp.UI
{
    public partial class MisReservas
    {
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        protected global::System.Web.UI.WebControls.Literal litSinReservas;
        protected global::System.Web.UI.WebControls.Repeater rptMisReservas;
    }
}
