//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Los campos declarados acá corresponden 1 a 1 a los controles con
//     runat="server" definidos en Registrarse.aspx. Si se agregan o
//     renombran controles en el .aspx, Visual Studio va a regenerar este
//     archivo automáticamente al guardar.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageUp.UI
{
    public partial class Registrarse
    {
        protected global::System.Web.UI.WebControls.Panel pnlDatosRegistro;
        protected global::System.Web.UI.WebControls.Panel pnlMensajeRegistro;
        protected global::System.Web.UI.WebControls.Literal litMensajeRegistro;

        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombre;

        protected global::System.Web.UI.WebControls.TextBox txtApellido;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvApellido;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;

        protected global::System.Web.UI.WebControls.TextBox txtConfirmarPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvConfirmarPassword;
        protected global::System.Web.UI.WebControls.CompareValidator cvPassword;

        protected global::System.Web.UI.WebControls.CheckBox chkAceptaTerminos;
        protected global::System.Web.UI.WebControls.CustomValidator cvAceptaTerminos;

        protected global::System.Web.UI.WebControls.CheckBox chkAceptaPoliticaPrivacidad;
        protected global::System.Web.UI.WebControls.CustomValidator cvAceptaPoliticaPrivacidad;

        protected global::System.Web.UI.WebControls.Button btnRegistrarse;

        protected global::System.Web.UI.WebControls.Panel pnlActivacion;
        protected global::System.Web.UI.WebControls.Panel pnlMensajeActivacion;
        protected global::System.Web.UI.WebControls.Literal litMensajeActivacion;

        protected global::System.Web.UI.WebControls.TextBox txtCodigoActivacion;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCodigoActivacion;

        protected global::System.Web.UI.WebControls.Button btnActivarCuenta;
        protected global::System.Web.UI.WebControls.LinkButton lnkReenviarCodigoActivacion;

        protected global::System.Web.UI.WebControls.Panel pnlExitoRegistro;
    }
}
